### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by krocheck** [bitfocus/companion-module-magewell-ultrastream#11]
https://github.com/bitfocus/companion-module-magewell-ultrastream/blob/042d398941e02ebb82f01d25a916cb45154eabb1/src/client.ts#L51

@Julusian I saw an unhandled exception for an `ETIMEDOUT` that traced back to here.  The `get()` commands all should have `.catch((e) => {}}` implemented?

@omeaart, fyi

**Comment by omeaart** [comment]
I hope to look into this after my holidays! :)
